function t142_checkSize(recid){var el=$("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed")}}}
function t347_setHeight(recid){var el=$('#rec'+recid);var div=el.find(".t347__table");var height=div.width()*0.5625;div.height(height)}
window.t347showvideo=function(recid){$(document).ready(function(){var el=$('#rec'+recid);var videourl='';var youtubeid=$("#rec"+recid+" .t347__video-container").attr('data-content-popup-video-url-youtube');if(youtubeid>''){videourl='https://www.youtube.com/embed/'+youtubeid}
$("#rec"+recid+" .t347__video-container").removeClass("t347__hidden");$("#rec"+recid+" .t347__video-carier").html("<iframe id=\"youtubeiframe"+recid+"\" class=\"t347__iframe\" width=\"100%\" height=\"100%\" src=\""+videourl+"?autoplay=1&rel=0\" frameborder=\"0\" allowfullscreen></iframe>")})}
window.t347hidevideo=function(recid){$(document).ready(function(){$("#rec"+recid+" .t347__video-container").addClass("t347__hidden");$("#rec"+recid+" .t347__video-carier").html("")})}
function t431_init(recid){var tableHead=t431__escapeHTML($('#rec'+recid+' .t431 .t431__data-part1').html()||"");var tableBody=t431__escapeHTML($('#rec'+recid+' .t431 .t431__data-part2').html()||"");var tableColSize=$('#rec'+recid+' .t431 .t431__table').attr("data-table-width");var hasTargetBlank=$('#rec'+recid+' .t431 .t431__table').attr("data-target-blank");var tHead=t431_parseData(tableHead);var tBody=t431_parseData(tableBody);var colSize=t431_parseData(tableColSize);var maxColNum=t431__findMaxRowLengthInTable(tHead,tBody);var colWidth=t431__setColumnsWidth(colSize,maxColNum,recid);var container=$('#rec'+recid+' .t431 .t431__table');var html="";if(tHead){html+=t431__generateTable(tHead,"th",hasTargetBlank,colWidth,maxColNum)}
if(tBody){html+=t431__generateTable(tBody,"td",hasTargetBlank,colWidth,maxColNum)}
container.append(html)}
function t431__findMaxRowLengthInTable(arrayHead,arrayData){var headMaxLength=0;var dataMaxLength=0;if(arrayHead){headMaxLength=t431__findMaxRowLengInArray(arrayHead)}
if(arrayData){dataMaxLength=t431__findMaxRowLengInArray(arrayData)}
if(dataMaxLength>headMaxLength){return dataMaxLength}else{return headMaxLength}}
function t431__escapeHTML(string){var html=string.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ');var result="";var allowedTags="";['b','i','u','ul','li','ol','br','img','s','sub','sup','span','hr','pre','code','mark','strong','small'].forEach(function(value){allowedTags+=":not("+value+")"});var allowedAttrs=['alt','class','title','id','src','style','width','height'];var fakeDOM=document.implementation.createHTMLDocument('fake');$.each($.parseHTML(html,fakeDOM)||[],function(i,$el){var el=$($el)[0];if(!$($el).is(allowedTags)){if(el.nodeType!==3){var temp=document.createElement(el.tagName);allowedAttrs.forEach(function(value){if(el.getAttribute(value)!==null){temp.setAttribute(value,el.getAttribute(value).replace(/javascript:/gi,''))}});temp.textContent=el.textContent;result+=temp.outerHTML}else{result+=el.textContent}}});return result}
function t431__findMaxRowLengInArray(curArray){var maxLength=0;for(var i=0;i<curArray.length;i++){if(curArray[i].length>maxLength){maxLength=curArray[i].length}}
return maxLength}
function t431__setColumnsWidth(colWidth,colsNumber,recid){if(colWidth){return colWidth[0]}else{var tableWidth=$('#rec'+recid+' .t431 .t-container .t-col').width();return(tableWidth/colsNumber+"px")}}
function t431__generateTable(arrayValues,colTag,hasTargetBlank,colWidth,maxColNumber){var html="";var tag="";if(colTag=="td"){tag="tbody"}else{tag="thead"}
html+='<'+tag+' class="t431__'+tag+'">';for(var i=0;i<arrayValues.length;i++){if(colTag=="td"){if((i+1)%2>0){html+='<tr class="t431__oddrow">'}else{html+='<tr class="t431__evenrow">'}}else{html+='<tr>'}
var addingCols=0;if(arrayValues[i].length<maxColNumber){addingCols=maxColNumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+addingCols);j++){if(arrayValues[i][j]){var curWidth="";if(Array.isArray(colWidth)&&colWidth[j]){curWidth=colWidth[j].myText}else{curWidth=colWidth}
var ColWithAttr='';if(colTag=="td"){ColWithAttr='<td class="t431__td t-text" width="'+curWidth+'">'}else{ColWithAttr='<th class="t431__th t-title" width="'+curWidth+'">'}
if(arrayValues[i][j].myHref){var tBlank="";if(hasTargetBlank){tBlank="target=\"_blank\""}
var linkWithAttr="";var linkCloseTag="";if(arrayValues[i][j].myHrefType=="link"){linkWithAttr='<a href="'+arrayValues[i][j].myHref+'"'+tBlank+'>';linkCloseTag='</a>'}else{linkWithAttr='<div class="t431__btnwrapper"><a href="'+arrayValues[i][j].myHref+'"'+tBlank+' class="t-btn t-btn_sm"><table style="width:100%; height:100%"><tr><td>';linkCloseTag='</td></tr></table></a></div>'}
html+=ColWithAttr+linkWithAttr+arrayValues[i][j].myText+linkCloseTag+'</'+colTag+'>'}else{html+=ColWithAttr+arrayValues[i][j].myText+'</'+colTag+'>'}}else{html+='<'+colTag+' class="t431__'+colTag+'" width="'+curWidth+'">'+'</'+colTag+'>'}}
html+="</tr>"}
html+="</"+tag+">";return html}
function t431_parseData(data){if(data!==""&&typeof data!="undefined"){data=t431__addBrTag(data);var arrayTable=[];var arrayRow=[];var curItem={myText:"",myHref:"",myHrefType:""};var hasLink="";var hasLinkWithSpace="";var hasBtn="";var hasBtnWithSpace="";var endLine="";for(var i=0;i<data.length;i++){if(data[i]==";"&&!(data.slice(i-4,i)=="&lt;"||data.slice(i-4,i)=="&gt;"||data.slice(i-5,i)=="&amp;"||data.slice(i-6,i)=="&nbsp;")){arrayRow.push(curItem);curItem={myText:"",myHref:""};hasLink="";hasLinkWithSpace="";hasBtn="";hasBtnWithSpace=""}else{if(hasLink=="link="||hasLinkWithSpace==" link="||hasBtn=="button="||hasBtnWithSpace==" button="){if(curItem.myHref===""&&hasLink==="link="){curItem.myText=curItem.myText.slice(0,-5);curItem.myHrefType="link"}else{if(curItem.myHref===""&&hasLinkWithSpace===" link="){curItem.myText=curItem.myText.slice(0,-6);curItem.myHrefType="link"}else{if(curItem.myHref===""&&hasBtn==="button="){curItem.myText=curItem.myText.slice(0,-7);curItem.myHrefType="btn"}else{if(curItem.myHref===""&&hasBtnWithSpace===" button="){curItem.myText=curItem.myText.slice(0,-8);curItem.myHrefType="btn"}}}}
curItem.myHref+=(data[i])}else{curItem.myText+=(data[i]);hasLink=t431__checkSubstr("link=",hasLink,data[i]);hasLinkWithSpace=t431__checkSubstr(" link=",hasLinkWithSpace,data[i]);hasBtn=t431__checkSubstr("button=",hasBtn,data[i]);hasBtnWithSpace=t431__checkSubstr(" button=",hasBtnWithSpace,data[i])}
endLine=t431__checkSubstr("<br />",endLine,data[i]);if(endLine=="<br />"){if(curItem.myHref){curItem.myHref=curItem.myHref.slice(0,-6)}else{curItem.myText=curItem.myText.slice(0,-6)}
arrayRow.push(curItem);arrayTable.push(arrayRow);curItem={myText:"",myHref:""};hasLink="";hasLinkWithSpace="";hasBtn="";hasBtnWithSpace="";arrayRow=[]}}}
if(arrayRow.length>0||curItem.myText!==""){if(curItem!==""){arrayRow.push(curItem)}
arrayTable.push(arrayRow)}}
return arrayTable}
function t431__checkSubstr(targetSubstr,curSubstr,curSymbol){if(!curSubstr&&curSymbol==targetSubstr[0]){return curSymbol}else{if(curSubstr){for(var i=0;i<(targetSubstr.length-1);i++){if(curSubstr[curSubstr.length-1]==targetSubstr[i]&&curSymbol==targetSubstr[i+1]){return(curSubstr+=curSymbol)}}}}}
function t431__addBrTag(oldStringItem){var newStringItem="";for(var i=0;i<oldStringItem.length;i++){if(oldStringItem[i]=="\n"||oldStringItem[i]=="\r"){newStringItem+="<br />"}else{newStringItem+=oldStringItem[i]}}
return newStringItem.replace(/&nbsp;/g,' ')}
function t431_createTable(recid,tablehead,tabledata,tablecolsize,hastargetblank,btnstyles,t431__tdstyles,t431__thstyles,t431__oddrowstyles,t431__evenrowstyles){var t431__arrayColSize=t431_parseData(tablecolsize);var t431__arrayHead=t431_parseData(tablehead);var t431__arrayData=t431_parseData(tabledata);var t431__maxcolnumber=t431__findMaxRowLengthInTable(t431__arrayHead,t431__arrayData);var t431__colWidth=t431__setColumnsWidth(t431__arrayColSize,t431__maxcolnumber,recid);if(t431__colWidth[0].myText&&t431__colWidth[0].myText[t431__colWidth[0].myText.length-1]=="%"){for(var i=0;i<t431__colWidth.length;i++){t431__colWidth[i].myText=t431__colWidth[i].myText.slice(0,-1);t431__colWidth[i].myText+="vw"}}
var t431__container=$('#rec'+recid+' .t431 .t-container .t431__table');var t431__htmlTable="";if(t431__arrayHead){t431__htmlTable+=t431__generateHtml(recid,t431__arrayHead,"th",hastargetblank,t431__colWidth,btnstyles,t431__thstyles,null,null,t431__maxcolnumber)}
t431__container.append(t431__htmlTable);t431__htmlTable="";if(t431__arrayData){t431__htmlTable+=t431__generateHtml(recid,t431__arrayData,"td",hastargetblank,t431__colWidth,btnstyles,t431__tdstyles,t431__oddrowstyles,t431__evenrowstyles,t431__maxcolnumber)}
t431__container.append(t431__htmlTable)}
function t431__generateHtml(recid,arrayValues,coltag,hastargetblank,colWidth,btnstyles,colstyles,oddrowstyles,evenrowstyles,maxcolnumber){var t431__htmlpart="";if(coltag=="td"){var t431__theadorbodytag="tbody"}else{var t431__theadorbodytag="thead"}
t431__htmlpart+='<'+t431__theadorbodytag+' class="t431__'+t431__theadorbodytag+'">';var t431__firstbodyrowstyle="";if($('#rec'+recid+' .t431 .t-container .t431__thead th').length>0&&$('#rec'+recid+' .t431 .t-container .t431__thead th').css("border-bottom-width")[0]!="0"){t431__firstbodyrowstyle="border-top: 0 !important;"}
for(var i=0;i<arrayValues.length;i++){if(coltag=="td"){if((i+1)%2>0){t431__htmlpart+="<tr class=\"t431__oddrow\""+"style=\""+oddrowstyles+"\">"}else{t431__htmlpart+="<tr class=\"t431__evenrow\""+"style=\""+evenrowstyles+"\">"}}else{t431__htmlpart+="<tr>"}
var t431__addingcols=0;if(arrayValues[i].length<maxcolnumber){t431__addingcols=maxcolnumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+t431__addingcols);j++){if(arrayValues[i][j]){if(Array.isArray(colWidth)&&colWidth[j]){var t431__curWidth=colWidth[j].myText}else{var t431__curWidth=colWidth}
if(i==0&&coltag=="td"){var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+t431__firstbodyrowstyle+"\">"}else{var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"}
if(arrayValues[i][j].myHref){var t431__tblank="";if(hastargetblank){var t431__tblank="target=\"_blank\""}
if(arrayValues[i][j].myHrefType=="link"){var t431__linkwithattr="<a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+">";var t431__linkclosetag="</a>"}else{var t431__linkwithattr="<div class=\"t431__btnwrapper\"><a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+" class=\"t-btn t-btn_sm\" style=\""+btnstyles+"\"><table style=\"width:100%; height:100%;\"><tr><td>";var t431__linkclosetag="</td></tr></table></a></div>"}
t431__htmlpart+=t431__colwithattr+t431__linkwithattr+arrayValues[i][j].myText+t431__linkclosetag+"</"+coltag+">"}else{t431__htmlpart+=t431__colwithattr+arrayValues[i][j].myText+"</"+coltag+">"}}else{t431__htmlpart+="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"+"</"+coltag+">"}}
t431__htmlpart+="</tr>"}
t431__htmlpart+="</"+t431__theadorbodytag+">";return t431__htmlpart}
function t450_showMenu(recid){var el=$('#rec'+recid);$('body').addClass('t450__body_menushowed');el.find('.t450').addClass('t450__menu_show');el.find('.t450__overlay').addClass('t450__menu_show');$('.t450').bind('clickedAnchorInTooltipMenu',function(){t450_closeMenu()});el.find('.t450__overlay, .t450__close, a[href*=#]').click(function(){var url=$(this).attr('href');if(typeof url!='undefined'&&url!=''&&(url.substring(0,7)=='#price:'||url.substring(0,9)=='#submenu:')){return}
t450_closeMenu()});$(document).keydown(function(e){if(e.keyCode===27){$('body').removeClass('t390__body_popupshowed');$('.t390').removeClass('t390__popup_show')}})}
function t450_closeMenu(){$('body').removeClass('t450__body_menushowed');$('.t450').removeClass('t450__menu_show');$('.t450__overlay').removeClass('t450__menu_show')}
function t450_checkSize(recid){var el=$('#rec'+recid).find('.t450');var windowheight=$(window).height()-80;var contentheight=el.find(".t450__top").height()+el.find(".t450__rightside").height();if(contentheight>windowheight){setTimeout(function(){el.addClass('t450__overflowed');el.find(".t450__container").css('height','auto')},200)}}
function t450_appearMenu(recid){var el=$('#rec'+recid);var burger=el.find(".t450__burger_container");burger.each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t450__beforeready')){el.finish();el.removeClass("t450__beforeready")}}else{el.stop();el.addClass("t450__beforeready")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if($(window).scrollTop()+$(window).height()>=$(document).height()-hideoffset){if(!el.hasClass('t450__beforeready')){el.finish();el.addClass("t450__beforeready")}}else{if(appearoffset!=""){if($(window).scrollTop()>=appearoffset){el.stop();el.removeClass("t450__beforeready")}}else{el.stop();el.removeClass("t450__beforeready")}}}})}
function t450_initMenu(recid){var el=$('#rec'+recid).find('.t450');var hook=el.attr('data-tooltip-hook');if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid);e.preventDefault()})}
$('#rec'+recid).find('.t450__burger_container').click(function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid)});if(isMobile){$('#rec'+recid).find('.t-menu__link-item').each(function(){var $this=$(this);if($this.hasClass('t450__link-item_submenu')){$this.on('click',function(){setTimeout(function(){t450_checkSize(recid)},100)})}})}
t450_highlight()}
function t450_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t450__menu a[href='"+url+"']").addClass("t-active");$(".t450__menu a[href='"+url+"/']").addClass("t-active");$(".t450__menu a[href='"+pathname+"']").addClass("t-active");$(".t450__menu a[href='/"+pathname+"']").addClass("t-active");$(".t450__menu a[href='"+pathname+"/']").addClass("t-active");$(".t450__menu a[href='/"+pathname+"/']").addClass("t-active")}
function t453_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t453__item a[href='"+url+"']").addClass("t-active");$(".t453__item a[href='"+url+"/']").addClass("t-active");$(".t453__item a[href='"+pathname+"']").addClass("t-active");$(".t453__item a[href='/"+pathname+"']").addClass("t-active");$(".t453__item a[href='"+pathname+"/']").addClass("t-active");$(".t453__item a[href='/"+pathname+"/']").addClass("t-active")}
function t453_checkAnchorLinks(recid){if($(window).width()>=960){var t453_navLinks=$("#rec"+recid+" .t453__item a:not(.tooltipstered)[href*='#']");if(t453_navLinks.length>0){t453_catchScroll(t453_navLinks)}}}
function t453_catchScroll(t453_navLinks){var t453_clickedSectionId=null,t453_sections=new Array(),t453_sectionIdTonavigationLink={},t453_interval=100,t453_lastCall,t453_timeoutId,t453_offsetTop=$(".t453").attr("data-offset-top");if(typeof t453_offsetTop=="undefined"){t453_offsetTop=0}
t453_navLinks.each(function(){var t453_cursection=t453_getSectionByHref($(this));if(typeof t453_cursection.attr("id")!="undefined"){t453_sections.push(t453_cursection)}
t453_sectionIdTonavigationLink[t453_cursection.attr("id")]=$(this)});t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop);t453_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t453_navLinks.removeClass('t-active');t453_sectionIdTonavigationLink[t453_getSectionByHref($(this)).attr("id")].addClass('t-active');t453_clickedSectionId=t453_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t453_now=new Date().getTime();if(t453_lastCall&&t453_now<(t453_lastCall+t453_interval)){clearTimeout(t453_timeoutId);t453_timeoutId=setTimeout(function(){t453_lastCall=t453_now;t453_clickedSectionId=t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop)},t453_interval-(t453_now-t453_lastCall))}else{t453_lastCall=t453_now;t453_clickedSectionId=t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop)}})}
function t453_getSectionByHref(curlink){if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curlink.attr("href").substring(1)+"']")}
else{return $(".r[data-record-type='215']").has("a[name='"+curlink.attr("href").substring(1)+"']")}}
function t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,offsetTop){var t453_scrollPosition=$(window).scrollTop(),t453_valueToReturn=t453_clickedSectionId;$(t453_sections).each(function(e){var t453_curSection=$(this),t453_sectionTop=t453_curSection.offset().top,t453_id=t453_curSection.attr('id'),t453_navLink=t453_sectionIdTonavigationLink[t453_id];if(t453_scrollPosition>=(t453_sectionTop-offsetTop)||(t453_sections[0].attr("id")==t453_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(t453_clickedSectionId==null&&!t453_navLink.hasClass('t-active')){t453_navLinks.removeClass('t-active');t453_navLink.addClass('t-active');t453_valueToReturn=null}else{if(t453_clickedSectionId!=null&&t453_id==t453_clickedSectionId){t453_valueToReturn=null}}
return!1}});return t453_valueToReturn}
function t453_appearMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t453").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t453__beforeready')){el.removeClass('t453__beforeready')}}else{el.addClass('t453__beforeready')}}})}
function t454_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t454__list_item a[href='"+url+"']").addClass("t-active");$(".t454__list_item a[href='"+url+"/']").addClass("t-active");$(".t454__list_item a[href='"+pathname+"']").addClass("t-active");$(".t454__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t454__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t454__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t454_checkAnchorLinks(recid){if($(window).width()>=960){var t454_navLinks=$("#rec"+recid+" .t454__list_item a:not(.tooltipstered)[href*='#']");if(t454_navLinks.length>0){setTimeout(function(){t454_catchScroll(t454_navLinks)},500)}}}
function t454_catchScroll(t454_navLinks){var t454_clickedSectionId=null,t454_sections=new Array(),t454_sectionIdTonavigationLink=[],t454_interval=100,t454_lastCall,t454_timeoutId;t454_navLinks=$(t454_navLinks.get().reverse());t454_navLinks.each(function(){var t454_cursection=t454_getSectionByHref($(this));if(typeof t454_cursection.attr("id")!="undefined"){t454_sections.push(t454_cursection)}
t454_sectionIdTonavigationLink[t454_cursection.attr("id")]=$(this)});t454_updateSectionsOffsets(t454_sections);$(window).bind('resize',t_throttle(function(){t454_updateSectionsOffsets(t454_sections)},200));$('.t454').bind('displayChanged',function(){t454_updateSectionsOffsets(t454_sections)});setInterval(function(){t454_updateSectionsOffsets(t454_sections)},5000);t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId);t454_navLinks.click(function(){var clickedSection=t454_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof clickedSection.attr("id")!="undefined"){t454_navLinks.removeClass('t-active');$(this).addClass('t-active');t454_clickedSectionId=t454_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t454_now=new Date().getTime();if(t454_lastCall&&t454_now<(t454_lastCall+t454_interval)){clearTimeout(t454_timeoutId);t454_timeoutId=setTimeout(function(){t454_lastCall=t454_now;t454_clickedSectionId=t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId)},t454_interval-(t454_now-t454_lastCall))}else{t454_lastCall=t454_now;t454_clickedSectionId=t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId)}})}
function t454_updateSectionsOffsets(sections){$(sections).each(function(){var t454_curSection=$(this);t454_curSection.attr("data-offset-top",t454_curSection.offset().top)})}
function t454_getSectionByHref(curlink){var curLinkValue=curlink.attr('href').replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curLinkValue+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+curLinkValue+"']")}}
function t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId){var t454_scrollPosition=$(window).scrollTop(),t454_valueToReturn=t454_clickedSectionId;if(t454_sections.length!=0&&t454_clickedSectionId==null&&t454_sections[t454_sections.length-1].attr("data-offset-top")>(t454_scrollPosition+300)){t454_navLinks.removeClass('t-active');return null}
$(t454_sections).each(function(e){var t454_curSection=$(this),t454_sectionTop=t454_curSection.attr("data-offset-top"),t454_id=t454_curSection.attr('id'),t454_navLink=t454_sectionIdTonavigationLink[t454_id];if(((t454_scrollPosition+300)>=t454_sectionTop)||(t454_sections[0].attr("id")==t454_id&&t454_scrollPosition>=$(document).height()-$(window).height())){if(t454_clickedSectionId==null&&!t454_navLink.hasClass('t-active')){t454_navLinks.removeClass('t-active');t454_navLink.addClass('t-active');t454_valueToReturn=null}else{if(t454_clickedSectionId!=null&&t454_id==t454_clickedSectionId){t454_valueToReturn=null}}
return!1}});return t454_valueToReturn}
function t454_setPath(){}
function t454_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t454").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t454_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-80px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t454_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t454_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t454"),burger=el.find(".t454__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t454_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t454_setLogoPadding(recid){if($(window).width()>980){var t454__menu=$('#rec'+recid+' .t454');var t454__logo=t454__menu.find('.t454__logowrapper');var t454__leftpart=t454__menu.find('.t454__leftwrapper');var t454__rightpart=t454__menu.find('.t454__rightwrapper');t454__leftpart.css("padding-right",t454__logo.width()/2+50);t454__rightpart.css("padding-left",t454__logo.width()/2+50)}}
function t509_setHeight(recid){var t509__el=$("#rec"+recid);var t509__image=t509__el.find(".t509__blockimg");t509__image.each(function(){var t509__width=$(this).attr("data-image-width");var t509__height=$(this).attr("data-image-height");var t509__ratio=t509__height/t509__width;var t509__padding=t509__ratio*100;$(this).css("padding-bottom",t509__padding+"%")});if($(window).width()>960){var t509__textwr=t509__el.find(".t509__textwrapper");var t509__deskimg=t509__el.find(".t509__desktopimg");t509__textwr.each(function(){$(this).css("height",t509__deskimg.innerHeight())})}}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=$('#rec'+recid);var play=el.find('.t670__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t670_hide(recid){var el=$('#rec'+recid);var body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=$('#rec'+recid);var image=el.find('.t670__separator');image.each(function(){var width=$(this).attr('data-slider-image-width');var height=$(this).attr('data-slider-image-height');var ratio=height/width;var padding=ratio*100;$(this).css('padding-bottom',padding+'%')})}
function t678_onSuccess(t678_form){var t678_inputsWrapper=t678_form.find('.t-form__inputsbox');var t678_inputsHeight=t678_inputsWrapper.height();var t678_inputsOffset=t678_inputsWrapper.offset().top;var t678_inputsBottom=t678_inputsHeight+t678_inputsOffset;var t678_targetOffset=t678_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t678_target=t678_targetOffset-200}else{var t678_target=t678_targetOffset-100}
if(t678_targetOffset>$(window).scrollTop()||($(document).height()-t678_inputsBottom)<($(window).height()-100)){t678_inputsWrapper.addClass('t678__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t678_target},400);setTimeout(function(){t678_inputsWrapper.addClass('t678__inputsbox_hidden')},400)}
var successurl=t678_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t706_onSuccessCallback(t706_form){$(".t706__cartwin-products").slideUp(10,function(){});$(".t706__cartwin-bottom").slideUp(10,function(){});$(".t706 .t-form__inputsbox").slideUp(700,function(){});try{tcart__unlockScroll()}catch(e){}}
function t712_onSuccess(t712_form){var t712_inputsWrapper=t712_form.find('.t-form__inputsbox');var t712_inputsHeight=t712_inputsWrapper.height();var t712_inputsOffset=t712_inputsWrapper.offset().top;var t712_inputsBottom=t712_inputsHeight+t712_inputsOffset;var t712_targetOffset=t712_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t712_target=t712_targetOffset-200}else{var t712_target=t712_targetOffset-100}
if(t712_targetOffset>$(window).scrollTop()||($(document).height()-t712_inputsBottom)<($(window).height()-100)){t712_inputsWrapper.addClass('t712__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t712_target},400);setTimeout(function(){t712_inputsWrapper.addClass('t712__inputsbox_hidden')},400)}
var successurl=t712_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t712_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t754__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t754__hoverZoom_init(recid);t754_initPopup(recid);t754__updateLazyLoad(recid);t754__alignButtons_init(recid);if(typeof t_store_addProductQuantityEvents!=='undefined'){t754_initProductQuantity(recid)}},500)}
function t754_initProductQuantity(recid){var el=$('#rec'+recid);var productList=el.find(".t754__col, .t754__product-full");productList.each(function(i,product){t_store_addProductQuantityEvents($(product))})}
function t754__showMore(recid){var el=$('#rec'+recid).find(".t754");var showmore=el.find('.t754__showmore');var cards_count=parseInt(el.attr('data-show-count'),10);if(cards_count>0){if(showmore.text()===''){showmore.find('td').text(t754__dict('loadmore'))}
showmore.show();el.find('.t754__col').hide();var cards_size=el.find('.t754__col').size();var cards_count=parseInt(el.attr('data-show-count'),10);var x=cards_count;var y=cards_count;t754__showSeparator(el,x);el.find('.t754__col:lt('+x+')').show();showmore.click(function(){x=(x+y<=cards_size)?x+y:cards_size;el.find('.t754__col:lt('+x+')').show();if(x==cards_size){showmore.hide()}
if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
t754__showSeparator(el,x);if($('#rec'+recid).find('[data-buttons-v-align]')[0]){t754__alignButtons(recid)}})}}
function t754__showSeparator(el,x){el.find('.t754__separator_number').addClass('t754__separator_hide');el.find('.t754__separator_hide').each(function(){if($(this).attr('data-product-separator-number')<=x){$(this).removeClass('t754__separator_hide')}})}
function t754__dict(msg){var dict=[];dict.loadmore={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var lang=window.browserLang;if(typeof dict[msg]!=='undefined'){if(typeof dict[msg][lang]!=='undefined'&&dict[msg][lang]!=''){return dict[msg][lang]}else{return dict[msg].EN}}
return 'Text not found "'+msg+'"'}
function t754__alignButtons_init(recid){var el=$('#rec'+recid);if(el.find('[data-buttons-v-align]')[0]){try{t754__alignButtons(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&$isMobile){return}
t754__alignButtons(recid)},200));el.find('.t754').bind('displayChanged',function(){t754__alignButtons(recid)});if($isMobile){$(window).on('orientationchange',function(){t754__alignButtons(recid)})}}catch(e){console.log('buttons-v-align error: '+e.message)}}}
function t754__alignButtons(recid){var rec=$('#rec'+recid);var wrappers=rec.find('.t754__textwrapper');var maxHeight=0;var itemsInRow=rec.find('.t-container').attr('data-blocks-per-row')*1;var mobileView=$(window).width()<=480;var tableView=$(window).width()<=960&&$(window).width()>480;var mobileOneRow=$(window).width()<=960&&rec.find('.t754__container_mobile-flex')[0]?!0:!1;var mobileTwoItemsInRow=$(window).width()<=480&&rec.find('.t754 .mobile-two-columns')[0]?!0:!1;if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var i=1;var wrappersInRow=[];$.each(wrappers,function(key,element){element.style.height='auto';if(itemsInRow===1){element.style.height='auto'}else{wrappersInRow.push(element);if(element.offsetHeight>maxHeight){maxHeight=element.offsetHeight}
$.each(wrappersInRow,function(key,wrapper){wrapper.style.height=maxHeight+'px'});if(i===itemsInRow){i=0;maxHeight=0;wrappersInRow=[]}
i++}})}
function t754__hoverZoom_init(recid){if(isMobile){return}
var rec=$('#rec'+recid);try{if(rec.find('[data-hover-zoom]')[0]){if(!jQuery.cachedZoomScript){jQuery.cachedZoomScript=function(url){var options={dataType:'script',cache:!0,url:url};return jQuery.ajax(options)}}
$.cachedZoomScript('https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js').done(function(script,textStatus){if(textStatus=='success'){setTimeout(function(){t_hoverZoom_init(recid,".t-slds__container")},500)}else{console.log('Upload script error: '+textStatus)}})}}catch(e){console.log('Zoom image init error: '+e.message)}}
function t754__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t754__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t754_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t754__product-'+lid_prod+'')})});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();t754_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]');el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0&&curUrl.indexOf('#%21%2Ftproduct%2F')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t754_updateSlider(recid+' #t754__product-'+lid_prod+'');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});if($('#record'+recid).length==0){t754_checkUrl(recid)}
t754_copyTypography(recid)}
function t754_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/');if(tprodIndex<0){tprodIndex=curUrl.indexOf('#%21%2Ftproduct%2F')}}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t754_updateSlider(recid){var el=$('#rec'+recid);t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t754_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t754_closePopup()}});el.find('.t-popup__close, .t754__close-text').click(function(e){t754_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t754_closePopup()}})}
function t754_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/');if(indexToRemove<0){indexToRemove=curUrl.indexOf('#%21%2Ftproduct%2F')}}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$(".t-popup").scrollTop(0);$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t754_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t754_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t754__title').attr('style');var descrStyle=rec.find('.t754__descr').attr('style');rec.find('.t-popup .t754__title').attr("style",t754_removeSizeStyles(titleStyle));rec.find('.t-popup .t754__descr, .t-popup .t754__text').attr("style",t754_removeSizeStyles(descrStyle))}
function t780_init(recid){if($("#rec"+recid+" .t-slds").length){t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})}
setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)})},500);$('#rec'+recid).find('.t780').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}
function t825_initPopup(recid){var rec=$('#rec'+recid);$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t825__popup');var analitics=el.attr('data-track-popup');var hook="TildaSendMessageWidget"+recid;var obj=$('#rec'+recid+' .t825__btn');obj.click(function(e){if(obj.hasClass('t825__btn_active')){t825_closePopup(rec);return}
obj.addClass('t825__btn_active');$('#rec'+recid+' .t825').addClass('t825_active');t825_showPopup(recid);e.preventDefault();if(analitics>''){Tilda.sendEventToStatistics(analitics,hook)}});if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t825_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t825__popup');el.find('.t825__btn_wrapper').removeClass('t825__btn_animate');el.find('.t825__btn-text').css('display','none');if($(window).width()<960){$('body').addClass('t825__body_popupshowed')}
popup.css('display','block');setTimeout(function(){popup.addClass('t825__popup_show')},50);el.find('.t825__mobile-icon-close').click(function(e){t825_closePopup(el)});$(document).keydown(function(e){if(e.keyCode==27){t825_closePopup(el)}});if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t825_closePopup(rec){if($(window).width()<960){$('body').removeClass('t825__body_popupshowed')}
rec.find('.t825').removeClass('t825_active');rec.find('.t825__btn').removeClass('t825__btn_active');rec.find('.t825__popup').removeClass('t825__popup_show');setTimeout(function(){rec.find('.t825__popup').not('.t825__popup_show').css('display','none')},300)}
function t825_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t859_init(recid){var rec=$('#rec'+recid);var container=rec.find('.t859');var doResize;t859_unifyHeights(rec);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!="undefined"&&window.noAdaptive==!0&&$isMobile){return}
t859_unifyHeights(rec)}));$(window).load(function(){t859_unifyHeights(rec)});rec.find('.t859').bind('displayChanged',function(){t859_unifyHeights(rec)});if(container.hasClass('t859__previewmode')){setInterval(function(){t859_unifyHeights(rec)},5000)}}
function t859_unifyHeights(rec){if($(window).width()>=960){rec.find('.t859 .t-container .t859__row').each(function(){var highestBox=0;var currow=$(this);$('.t859__inner-col',this).each(function(){var curCol=$(this);var curWrap=curCol.find('.t859__wrap');var curColHeight=curWrap.outerHeight();if(curColHeight>highestBox){highestBox=curColHeight}});$('.t859__inner-col',this).css('height',highestBox)})}else{$('.t859__inner-col').css('height','auto')}}